# Generated by Django 6.1.1 on 2026-09-29 08:45

import django.db.models.deletion
import django.utils.timezone
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='5-letter uppercase English word', max_length=5, unique=True, validators=[game.models.validate_five_letter_word])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this word is available for active gameplay.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_word', models.CharField(max_length=5)),
                ('max_attempts', models.IntegerField(default=5)),
                ('attempts_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('WON', 'WON'), ('LOST', 'LOST')], default='IN_PROGRESS', max_length=20)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('guess_word', models.CharField(max_length=5)),
                ('guessed_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.gamesession')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
    ]
